form:
  path: /form
  controller: App\Controller\SurveyController::form
  
save_form:
  path: /save-form
  controller: App\Controller\SurveyController::saveForm

get_user:
  path: /get-user
  controller: App\Controller\SurveyController::getUser  
  
view_user:
  path: /view-user
  controller: App\Controller\SurveyController::viewUser